name: Build & Deploy Backend to VPS

on:
  push:
    branches: [ "main", "qa" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dabaservices/macbook-back-template

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      # --- בנייה ודחיפה ---
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name == 'main' && 'latest' || 'qa' }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            if [ "${{ github.ref_name }}" == "main" ]; then
              echo "Deploying Main Environment..."
              cd /opt/app/daba-system
              docker compose pull
              docker compose up -d
            
            elif [ "${{ github.ref_name }}" == "qa" ]; then
              echo "Deploying QA Environment..."
              cd /opt/app/daba-qa
              docker compose pull
              docker compose up -d
              
              echo "Deploying AUTO Environment..."
              cd /opt/app/daba-auto
              # סביבת Auto משתמשת באימג' של ה-QA בבקאנד, 
              # אז הפול כאן יעדכן אותה אוטומטית לקוד החדש!
              docker compose pull
              docker compose up -d
            fi
            
            docker image prune -af
